x-healthcheck: &x-healthcheck
  test: curl --fail http://127.0.0.1 || exit 1
  interval: 60s
  retries: 5
  start_period: 20s
  timeout: 10s

x-service: &x-service-base
  container_name: base
  restart: always
  expose:
    - ${SERVICE_PORT}
  environment:
    LOG_LEVEL: ${LOG_LEVEL}
  volumes:
    #- /app/onlyoffice/CommunityServer/data:/app/onlyoffice/data
    - ${VOLUMES_DIR:+${VOLUMES_DIR}/}app_data:/app/onlyoffice/data

services:
  onlyoffice-health-checks-ui:
    <<: *x-service-base
    image: "${REGISTRY}${REPO}/${DOCKER_IMAGE_PREFIX}-healthchecks:${DOCKER_TAG}"
    container_name: ${HEALTHCHECKS_HOST}
    healthcheck:
     <<: *x-healthcheck
     test: curl --fail http://${SERVICE_HEALTHCHECKS}/liveness/ || exit 1
networks:
  default:
    name: ${NETWORK_NAME}
    external: true

volumes:
  app_data:
